trigger: none # will disable CI builds entirely

pr:
  - master

pool:
  vmImage: 'windows-2019'
  
steps:

- checkout: self
  clean: true
  lfs: false
  persistCredentials: false

- task: WinAppDriverInstaller@0
  inputs:
    WinAppDriverVersion: 'v1.1.1'
    
- task: CmdLine@2
  displayName: yarn install
  inputs:
    script: yarn install

- task: CmdLine@2
  displayName: yarn run prepublishOnly
  inputs:
    script: yarn run prepublishOnly

- task: PowerShell@2
  displayName: 'Replace the AppID'
  inputs:
    targetType: 'inline'
    script: '((Get-Content -path example/Setup.ts -Raw) -replace "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","Microsoft.WindowsCalculator.Dev_8wekyb3d8bbwe!App") | Set-Content -Path example/Setup.ts'
- task: PowerShell@2
  displayName: 'Show the AppID'
  inputs:
    targetType: 'inline'
    script: 'Get-Content example/Setup.ts | foreach {Write-Output $_}'

- task: CmdLine@2
  displayName: yarn install
  inputs:
    script: yarn install
    workingDirectory: 'example'

- task: DeleteFiles@1
  displayName: Remove offical selenium-appium\dist
  inputs:
    SourceFolder: 'example\node_modules\selenium-appium\dist'
    Contents: '*'

- task: CopyFiles@2
  displayName: copy built selenium-appium\dist
  inputs:
    SourceFolder: 'dist'
    Contents: '**'
    TargetFolder: 'example\node_modules\selenium-appium\dist'
    OverWrite: true

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'react-native-windows'
    userRepository: 'react-native-windows/CalculatorPackage'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/*.zip'
    destinationFolder: 'TestApp'
    cleanDestinationFolder: true

- task: PowerShell@1
  displayName: 'Install Calculator Cert'
  inputs:
    scriptType: inlineScript
    arguments: '-NonInteractive -Verb RunAs'
    inlineScript: |
      $file = ( Get-ChildItem -Path TestApp\Calculator_$(PackageManifest)_Test\Calculator_$(PackageManifest)_x64.cer )
      $file | Import-Certificate -CertStoreLocation cert:\LocalMachine\Root


- task: PowerShell@1
  displayName: 'Install Calculator Packages'
  inputs:
    scriptName: 'TestApp\Calculator_$(PackageManifest)_Test\Add-AppDevPackage.ps1'
    arguments: '-NonInteractive -Force:$true  -Verb RunAs'

- task: Windows Application Driver@0
  inputs:
    OperationType: 'Start'
    WADArguments: 127.0.0.1 4723/wd/hub
    AgentResolution: 1080p
    
- task: CmdLine@2
  inputs:
    script: 'yarn run jest'
    workingDirectory: 'example'

- task: Windows Application Driver@0
  inputs:
    OperationType: 'Stop'
  condition: succeededOrFailed()

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'example/test-report.xml'
  condition: succeededOrFailed()